### ISSUE TITLE
Betere zichtbaar in welk deel van werkorden je zit (Comment by Ton)

### ISSUE THREAD

**Issue by artvabas** [artvabas/RepairCafeCureApp#38]
Logo’s aanpassen, het blijft onduidelijk waar je in het programma zit. Logo voor Open, Progress en Repaired zijn allemaal gelijk.
Liever zie ik de kleur van de tabtoets in de banner een permanente kleur krijgen tot een andere tabtoets wordt ingedrukt. Hij verkleurt nu alleen wanneer je er met je muis boven zit.

**Comment by artvabasDev** [comment]
See #42
Added highlghts options under category General-> (new) Accessibility -> Highlights option., choices that can be made are:

1. Highlight Ribbon Button only when the button is in a panel with more buttons (Standard- Category group)
2. Allways highlight Ribbon Buttons after selecting.
3. None

Also added a setting for show hiding the status-bar General -> View -> Show status bar

**Comment by artvabas** [comment]
De iconen (logo's) hebben niets te maken met open, progress en repaired maar met de view wat actief zichtbaar is in het programma. Ofwel open, progress en repaired delen allen dezelfde view, alleen zijn er andere bewerkingen in deze view mogelijk, aan de hand van welke optie (open, progress en repaired) je gekozen hebt.

Net zoals onder reports de opties contribution en pin ook dezelfde view delen, namelijk de view finance.

Daarom zullen deze iconen niet veranderd worden op de manier zoals hierboven wordt voorgesteld (andere iconen in werkorder-view voor open, progress en repaired).

Waarom? Ten eerste werd al visueel aangegeven in welke deel van programma je zit in titelbalk van het applicatiescherm.

Nu is er speciaal voor de werkorder-view de status van werkorders zichtbaar onder existing workorders zichtbaar gemaakt.

Plus de mogelijkheid om de knoppen ge-highlight te laten na het selecteren. Deze staat standaard aan voor deelknoppen met dezelfde view:
![image](https://github.com/user-attachments/assets/83afe51b-27bb-4ef8-9061-648d69b3286c)
![image](https://github.com/user-attachments/assets/965b02c8-0434-4ae6-9663-960b333e09b0)
